import React from "react";
import {
  Avatar,
  AvatarFallback,
  AvatarImage,
} from "@/components/ui/avatar";
import { Card, CardContent } from "@/components/ui/card";

const testimonialData = [
  // First row
  [
    {
      rating: 5,
      text: "Since implementing this CRM, our sales have increased by 30% in just three months. It's become an integral part of our growth strategy.",
      name: "Marx Hershey",
      title: "Project Manager",
      avatar: "/images/migrated-homepage/image-10.png",
    },
    {
      rating: 5,
      text: "This CRM has transformed how we interact with our customers. The marketing automation and customer insights have been game-changers for us. Highly recommended!",
      name: "Tyra Dhillon",
      title: "Software Tester",
      avatar: "/images/migrated-homepage/image-9.png",
    },
    {
      rating: 5,
      text: "I was looking for a CRM that was easy to use and could adapt to my business. This CRM has exceeded my expectations. It's simple, intuitive, and customizable.",
      name: "Courtney Henry",
      title: "UI/UX Designer",
      avatar: "/images/migrated-homepage/image-2.png",
    },
    {
      rating: 5,
      text: "The sales pipeline and automation tools have been a massive time-saver. We can now manage leads and deals more efficiently, which has had a direct impact on our bottom line.",
      name: "Marvin McKinney",
      title: "Team Leader",
      avatar: "/images/migrated-homepage/image-11.png",
    },
  ],
  // Second row
  [
    {
      rating: 5,
      text: "The reports generated by this CRM have allowed us to track and measure our performance better than ever. It's helped us identify areas for improvement and growth opportunities.",
      name: "Roselle Ehrman",
      title: "Software Developer",
      avatar: "/images/migrated-homepage/image-12.png",
    },
    {
      rating: 5,
      text: "The ability to segment customers and personalize our marketing campaigns has led to a significant increase in conversion rates. It's been a game-changer for our e-commerce business.",
      name: "Floyd Miles",
      title: "Software Development Manager",
      avatar: "/images/migrated-homepage/image-5.png",
    },
    {
      rating: 5,
      text: "Our customer support has become more organized and efficient with this CRM. The ticketing system and knowledge base features have made a significant difference in how we serve our customers.",
      name: "Lauralee Quintero",
      title: "Scrum Master",
      avatar: "/images/migrated-homepage/image-6.png",
    },
    {
      rating: 5,
      text: "The collaboration features in this CRM have greatly improved how our teams work together. Sharing information and coordinating has never been easier.",
      name: "Kylee Danford",
      title: "Ethical Hacker",
      avatar: "/images/migrated-homepage/image-7.png",
    },
    {
      rating: 5,
      text: "This CRM seamlessly integrated with our existing systems. The implementation was a breeze, and it's made a significant difference in our data management.",
      name: "Dianne Russell",
      title: "Scrum Master",
      avatar: "/images/migrated-homepage/image-8.png",
    },
  ],
  // Third row
  [
    {
      rating: 5,
      text: "This CRM has transformed how we interact with our customers. The marketing automation and customer insights have been game-changers for us. Highly recommended!",
      name: "Tyra Dhillon",
      title: "Software Tester",
      avatar: "/images/migrated-homepage/image-9.png",
    },
    {
      rating: 5,
      text: "Since implementing this CRM, our sales have increased by 30% in just three months. It's become an integral part of our growth strategy.",
      name: "Marx Hershey",
      title: "Project Manager",
      avatar: "/images/migrated-homepage/image-10.png",
    },
    {
      rating: 5,
      text: "The sales pipeline and automation tools have been a massive time-saver. We can now manage leads and deals more efficiently, which has had a direct impact on our bottom line.",
      name: "Marvin McKinney",
      title: "Team Leader",
      avatar: "/images/migrated-homepage/image-11.png",
    },
    {
      rating: 5,
      text: "The reports generated by this CRM have allowed us to track and measure our performance better than ever. It's helped us identify areas for improvement and growth opportunities.",
      name: "Roselle Ehrman",
      title: "Software Developer",
      avatar: "/images/migrated-homepage/image-12.png",
    },
  ],
];

export const TestimonialSection = (): JSX.Element => {
  const renderStars = (rating: number) => {
    return Array.from({ length: 5 }, (_, index) => (
      <img
        key={index}
        className="w-6 h-6"
        alt="Star rating"
        src={
          index < rating
            ? "/images/migrated-homepage/stars-new.svg"
            : "/images/migrated-homepage/stars-new-1.svg"
        }
      />
    ));
  };

  return (
    <section className="flex flex-col items-center justify-center gap-12 px-20 py-24 w-full bg-white">
      <header className="flex flex-col items-center justify-center gap-4 w-full translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:0ms]">
        <h2 className="w-full mt-[-1.00px] font-heading-desktop-h2 font-[number:var(--heading-desktop-h2-font-weight)] text-black text-[length:var(--heading-desktop-h2-font-size)] text-center tracking-[var(--heading-desktop-h2-letter-spacing)] leading-[var(--heading-desktop-h2-line-height)] [font-style:var(--heading-desktop-h2-font-style)]">
          Used by more than 10K+ Business
        </h2>

        <p className="w-full font-body-extra-large-regular font-[number:var(--body-extra-large-regular-font-weight)] text-[#717171] text-[length:var(--body-extra-large-regular-font-size)] text-center tracking-[var(--body-extra-large-regular-letter-spacing)] leading-[var(--body-extra-large-regular-line-height)] [font-style:var(--body-extra-large-regular-font-style)]">
          Hear what they say about TheGridHub and why you should choose our CRM
        </p>
      </header>

      <div className="flex flex-col items-center justify-center gap-6 w-full overflow-hidden translate-y-[-1rem] animate-fade-in opacity-0 [--animation-delay:200ms]">
        {testimonialData.map((row, rowIndex) => (
          <div
            key={rowIndex}
            className={`inline-flex items-start gap-6 flex-[0_0_auto] ${
              rowIndex === 0
                ? "ml-[-217.33px] mr-[-217.33px]"
                : rowIndex === 1
                  ? "ml-[-434.67px] mr-[-434.67px]"
                  : "ml-[-217.33px] mr-[-217.33px]"
            }`}
          >
            {row.map((testimonial, cardIndex) => (
              <Card
                key={`${rowIndex}-${cardIndex}`}
                className="flex flex-col w-[410.67px] items-start gap-5 p-10 bg-white rounded-lg border border-solid border-[#e4e4e4]"
              >
                <CardContent className="p-0 flex flex-col gap-5 w-full">
                  <div className="flex items-start gap-1 w-full">
                    {renderStars(testimonial.rating)}
                  </div>

                  <div className="flex flex-col items-center gap-6 w-full">
                    <p className="w-full h-[100px] mt-[-1.00px] font-body-extra-large-medium font-[number:var(--body-extra-large-medium-font-weight)] text-black text-[length:var(--body-extra-large-medium-font-size)] tracking-[var(--body-extra-large-medium-letter-spacing)] leading-[var(--body-extra-large-medium-line-height)] overflow-hidden text-ellipsis [display:-webkit-box] [-webkit-line-clamp:3] [-webkit-box-orient:vertical] [font-style:var(--body-extra-large-medium-font-style)]">
                      {testimonial.text}
                    </p>

                    <div className="flex items-center gap-3 w-full">
                      <Avatar className="w-10 h-10">
                        <AvatarImage
                          src={testimonial.avatar}
                          alt={testimonial.name}
                          className="rounded-[100px] object-cover"
                        />
                        <AvatarFallback className="rounded-[100px]">
                          {testimonial.name
                            .split(" ")
                            .map((n) => n[0])
                            .join("")}
                        </AvatarFallback>
                      </Avatar>

                      <div className="inline-flex flex-col items-start justify-center gap-[3px]">
                        <div className="w-fit mt-[-1.00px] font-body-large-medium font-[number:var(--body-large-medium-font-weight)] text-black text-[length:var(--body-large-medium-font-size)] tracking-[var(--body-large-medium-letter-spacing)] leading-[var(--body-large-medium-line-height)] whitespace-nowrap [font-style:var(--body-large-medium-font-style)]">
                          {testimonial.name}
                        </div>

                        <div className="w-fit font-body-base-regular font-[number:var(--body-base-regular-font-weight)] text-[#aeaeae] text-[length:var(--body-base-regular-font-size)] tracking-[var(--body-base-regular-letter-spacing)] leading-[var(--body-base-regular-line-height)] whitespace-nowrap [font-style:var(--body-base-regular-font-style)]">
                          {testimonial.title}
                        </div>
                      </div>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        ))}

        <div className="absolute w-[928px] h-[1280px] top-[-172px] left-44 rotate-90 bg-[linear-gradient(0deg,rgba(255,255,255,1)_0%,rgba(255,255,255,0)_19%,rgba(255,255,255,0)_86%,rgba(255,255,255,1)_100%)]" />
      </div>
    </section>
  );
};
